[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''local final_scoring_hand = {}'''
position = "before"
payload = '''
SMODS.calculate_context({mul_add_to_play = true})
'''
match_indent = true