[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''if type(args.operation) == 'function' then'''
position = "before"
payload = '''
for _, key in ipairs(Multiverse.DeckEnchantment.obj_buffer) do
    local obj = Multiverse.DeckEnchantments[key]
    local data = G.GAME.mul_deck_enchantments[key]
    if data and data.level > 0 and obj.calc_scaling and type(obj.calc_scaling) == "function" then
        local ret = obj:calc_scaling(data, card, initial, scalar_value, args)
        if ret then
            if ret.override_value and not args.block_overrides.value then initial = ret.override_value.value; SMODS.calculate_effect(ret.override_value, _card) end
            if ret.override_scalar_value and not args.block_overrides.scalar then scalar_value = ret.override_scalar_value.value; SMODS.calculate_effect(ret.override_scalar_value, _card) end
            if ret.override_message and not args.block_overrides.message then scaling_message = SMODS.merge_defaults(ret.override_message, scaling_message) end
            if ret.post then ret.post.source = obj; scaling_responses[#scaling_responses + 1] = ret.post end
            SMODS.calculate_effect(ret, G.deck.cards[1] or G.deck)
        end
    end
end
'''
match_indent = true