[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''
else 
    G.hand.highlighted[i].ability.discarded = true
    draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])
end
'''
position = "before"
payload = '''
elseif G.hand.highlighted[i].ability.set == "mul_Skill" and hook and G.hand.highlighted[i].config.center.sneaky then
    sneaky_cards[#sneaky_cards + 1] = G.hand.highlighted[i]
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''
-- TARGET: pre_discard
'''
position = "after"
payload = '''
local sneaky_cards = {}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''
if not hook then
'''
position = "before"
payload = '''
if #sneaky_cards > 0 then
    G.E_MANAGER:add_event(Event({
        func = function()
            G.E_MANAGER:add_event(Event({
                func = function()
                    Multiverse.handle_sneaky_trigggers(sneaky_cards)
                    return true
                end
            }))
            return true
        end
    }))
end
'''
match_indent = true
