[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''=[SMODS blindexpander "blindexpander.lua"]'''
pattern = '''
G.GAME.blind.original_blind = G.GAME.blind.original_blind or G.GAME.blind.config.blind.key
'''
position = "after"
payload = '''
if G.GAME.blind.original_blind == "bl_mul_spire_shield" then
    G.GAME.blind.original_blind = "bl_mul_corrupt_heart"
end
'''
match_indent = true
