[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''            SMODS.calculate_context({end_of_round = true, game_over = game_over, beat_boss = G.GAME.blind.boss })'''
position = "after"
payload = '''
SMODS.calculate_context({mul_philosophers_stone_check = true, game_over = game_over, beat_boss = G.GAME.blind.boss })
'''
match_indent = true
