[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''
elseif not self.greyed then
    self.children.center:draw_shader('dissolve')
'''
position = "before"
payload = '''
elseif Multiverse.is_valid_half(self) or (self.config.center_key == "m_mul_frankenstein" and Multiverse.is_valid_frankenstein(self)) then
    -- dont render base here as well
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''
elseif not self.greyed then
    if self.children.front and (self.ability.delayed or not self:should_hide_front()) then
'''
position = "before"
payload = '''
elseif Multiverse.is_valid_half(self) then
    if self.ability.mul_half_card == "left" then
        self.children.front:draw_shader("mul_lefthalf", nil, self.ARGS.send_to_shader)
    else
        self.children.front:draw_shader("mul_righthalf", nil, self.ARGS.send_to_shader)
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if card and card.ability and (card.ability.extra_slots_used or 0) ~= 0 then
'''
position = "before"
payload = '''
if card and card.ability and Multiverse.is_valid_half(card) then
    if card.ability.mul_half_card == "left" then
        info_queue[#info_queue + 1] = Multiverse.DummyCenters["du_mul_half_left"]
    else
        info_queue[#info_queue + 1] = Multiverse.DummyCenters["du_mul_half_right"]
    end
end
'''
match_indent = true