[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
e.config.ref_table:use_consumeable(area)
'''
position = "after"
payload = '''
if card.config.center.key == "c_mul_philosophers_stone" then
    dont_dissolve = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
if not dont_dissolve then card:start_dissolve() end
'''
position = "after"
payload = '''
if card.config.center.key == "c_mul_philosophers_stone" then
    G.E_MANAGER:add_event(Event({
        trigger = 'after',
        blockable = false,
        delay =  1.05,
        func = function()
            area:remove_card(card)
            card:remove()
            card = nil
            return true
        end
    }))
    G.E_MANAGER:add_event(Event({
        trigger = 'after',
        blockable = false,
        delay =  1.051,
    }))
end
'''
match_indent = true
