[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.R, config={align = "cm", id = 'row_round'}, nodes={
    {n=G.UIT.C, config={align = "cm"}, nodes=contents.buttons},
    {n=G.UIT.C, config={align = "cm"}, nodes=contents.round}
}},
'''
position = "after"
payload = '''
Multiverse.thaumaturgy_UI_row(temp_col, temp_col2, scale),
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
blind_chips = self.HUD_blind:get_UIE_by_ID('HUD_blind_count'),
'''
position = "after"
payload = '''
mul_thaumaturgy_energy = self.HUD:get_UIE_by_ID("thaumaturgy_UI_count"),
'''
match_indent = true
