[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''
self.config.h_popup = create_UIBox_detailed_tooltip(self.config.detailed_tooltip)
self.config.h_popup_config ={align="tm", offset = {x=0,y=-0.1}, parent = self}
'''
position = "after"
payload = '''
if self.config.detailed_tooltip_align then
    self.config.h_popup_config.align = self.config.detailed_tooltip_align
end
if self.config.detailed_tooltip_offset then
    self.config.h_popup_config.offset = self.config.detailed_tooltip_offset
end
'''
match_indent = true
