---@meta

---@class Anchor
---@field x_alignment? "l" | "c" | "r"
---@field y_alignment? "b" | "c" | "t"
---@field x_offset number?
---@field y_offset number?
---@field x_scale number?
---@field y_scale number?
---@field rotation number?
---@field target Moveable?
---@field inner_align boolean?

---@class Multiverse.Animation
---@field path string The name of the file where the animation is stored
---@field frames integer The number of frames the animation has
---@field columns integer? The number of columns the spritesheet has. Do not include if the spritesheet is all in one row.
---@field px integer The width of an individual frame of the animation
---@field py integer The height of an individual frame of the animation
---@field key string The key of the animation
---@field is_continuous boolean? Whether or not this animation is supposed to run continuously
---@field duration number The amount of time that one animation loop will take
---@field frame_data love.Quad[] The quadrants of the file that each represent a single frame
---@field image love.Image The image where all the quadrants are derived from
---@field anchor Anchor The place on the screen where the video is
---@field no_stretch boolean?

---@class Multiverse.Video
---@field path string The name of the file where the video is stored
---@field key string The key of the video.
---@field volume number? The volume of the video
---@field video love.Video The video to be displayed
---@field anchor Anchor The place on the screen where the video is
---@field px? integer The width of an individual frame of the video
---@field py? integer The height of an individual frame of the video
---@field no_stretch boolean?

---@class Multiverse.Drawable
---@field key string
---@field anchor Anchor
---@field update fun(self: Multiverse.Drawable)
---@field _removed? boolean
---@field _paused? boolean
---@field _progress? number
---@field drawable love.Video | love.Image
---@field ref_obj Multiverse.Animation | Multiverse.Video
