---@meta

---@class CalcContext
---@field mul_philosophers_stone_check? boolean True after the end of round context happens. Used for checking if a Philosopher's Stone should spawn.
---@field mul_highlighted? boolean Whether or not a playing card has been selected.
---@field mul_TP_altered? boolean True if TP has changed.
---@field mul_from_hand? boolean True if TP has changed because a hand didn't oneshot the blind.
---@field mul_thaumaturgy_energy_altered? boolean True if Thaumaturgy Energy has changed.
---@field mul_from_philosophers_stone? boolean True if Thaumaturgy Energy has changed because a Philosopher's Stone was created.
---@field mul_from_charge? boolean True if Thaumaturgy Energy has changed because of end of round energy generation.
---@field mul_deck_enchantments_modified? boolean True if the deck's enchantments have changed.
---@field mul_enchantment_removed? boolean True if an enchantment was removed from deck.
---@field mul_enchantment_applied? boolean True if an enchantment was applied to deck.
---@field mul_enchantment_object? Multiverse.DeckEnchantment The enchantment object of the enchantment whose level was modified.
---@field mul_change_skill_cost? boolean True if a Skill Card's cost is being calculated.
---@field mul_base_cost? integer The base cost of the Skill Card whose cost is being calculated.
---@field mul_enchantment_data? EnchantmentData The data that stores the affected enchantment's state.
---@field exhausted? Card[] A list of all cards that were exhausted.
---@field mul_exhaust_playing_cards? boolean Whether or not playing cards were exhausted.
---@field mul_post_discard? boolean True after all other discard effects.