---@meta

---@class Multiverse.SkillCard: SMODS.Enhancement
---@field super? SMODS.Enhancement|table Parent class.
---@field obj_buffer? Enhancements|string[] Array of keys to all objects registered to this class. 
---@field obj_table? table<Enhancements|string, Multiverse.SkillCard|table> Table of objects registered to this class. 
---@field replace_base_card? boolean Don't draw base card sprite or give base chips. 
---@field no_rank? boolean Enhanced cards have no rank
---@field no_suit? boolean Enhanced cards have no suit. 
---@field any_suit? boolean Enhanced cards have all suits. 
---@field overrides_base_rank? boolean Enhancement cannot be generated by consumables. Automatically set to `true` if Enhancement has `no_rank`. 
---@field always_scores? boolean Enhanced cards always score. 
---@field weight? number Weight of the enhancement. 
---@field __call? fun(self: Multiverse.SkillCard|table, o: Multiverse.SkillCard|table): nil|table|Multiverse.SkillCard
---@field extend? fun(self: Multiverse.SkillCard|table, o: Multiverse.SkillCard|table): table Primary method of creating a class. 
---@field check_duplicate_register? fun(self: Multiverse.SkillCard|table): boolean? Ensures objects already registered will not register. 
---@field check_duplicate_key? fun(self: Multiverse.SkillCard|table): boolean? Ensures objects with duplicate keys will not register. Checked on `__call` but not `take_ownership`. For take_ownership, the key must exist. 
---@field register? fun(self: Multiverse.SkillCard|table) Registers the object. 
---@field check_dependencies? fun(self: Multiverse.SkillCard|table): boolean? Returns `true` if there's no failed dependencies. 
---@field process_loc_text? fun(self: Multiverse.SkillCard|table) Called during `inject_class`. Handles injecting loc_text. 
---@field send_to_subclasses? fun(self: Multiverse.SkillCard|table, func: string, ...: any) Starting from this class, recusively searches for functions with the given key on all subordinate classes and run all found functions with the given arguments. 
---@field pre_inject_class? fun(self: Multiverse.SkillCard|table) Called before `inject_class`. Injects and manages class information before object injection. 
---@field post_inject_class? fun(self: Multiverse.SkillCard|table) Called after `inject_class`. Injects and manages class information after object injection. 
---@field inject_class? fun(self: Multiverse.SkillCard|table) Injects all direct instances of class objects by calling `obj:inject` and `obj:process_loc_text`. Also injects anything necessary for the class itself. Only called if class has defined both `obj_table` and `obj_buffer`. 
---@field inject? fun(self: Multiverse.SkillCard|table, i?: number) Called during `inject_class`. Injects the object into the game. 
---@field take_ownership? fun(self: Multiverse.SkillCard|table, key: string, obj: Multiverse.SkillCard|table, silent?: boolean): nil|table|Multiverse.SkillCard Takes control of vanilla objects. Child class must have get_obj for this to function
---@field get_obj? fun(self: Multiverse.SkillCard|table, key: string): Multiverse.SkillCard|table? Returns an object if one matches the `key`. 
---@field get_weight? fun(self: Multiverse.SkillCard|table): number? Used to modify the weight of the Enhancement. 
---@field tp_cost? number | "X"
---@field can_use_skill? fun(self: Multiverse.SkillCard|table, card: Card | table): boolean?
---@field use_skill? fun(self: Multiverse.SkillCard|table, card: Card | table, paid_amt: integer, x: integer?): onSkillUse? x is nil if the skill card does not cost X
---@field get_final_tp_cost? fun(self: Multiverse.SkillCard|table, card: Card | table, ui_format: boolean?): number | string
---@field generate_cost_ui? fun(self: Multiverse.SkillCard|table, card: Card | table)
---@field generate_use_ui? fun(self: Multiverse.SkillCard|table, card: Card | table)

---@overload fun(self: Multiverse.SkillCard): Multiverse.SkillCard
Multiverse.SkillCard = setmetatable({}, {
    __call = function(self)
        return self
    end
})

---@alias onSkillUse
---| "retain"
---| "discard" Default if no option is returned
---| "exhaust"
---| "destroy"
